### ISSUE TITLE
start-server.sh not found during execution

### ISSUE THREAD

**Issue by victorperin** [matm616/ProjectZomboidServer#1]
I'm getting this message when trying to run:

```
bash: /home/steam/projectzomboid-dedicated/start-server.sh -Xms4G -Xmx1G -adminpassword projectzomboidserver -servername server: No such file or directory
```

### How to reproduce
```
docker run matm616/projectzomboid
```
(using your docker hub built image)

**Comment by matm616** [comment]
I've already been working on a fix for this during the last few hours, a few changes will be pushed hopefully within a couple hours

**Comment by matm616** [comment]
Should be fixed now, let me know if it works for you @victorperin

**Comment by victorperin** [comment]
Thanks! :)
